### PR TITLE
Announce meeting on 19953

### PR DESCRIPTION
**Pull request by jnewbery**
Notes and questions to follow

Also adds a new 'taproot' component, so that a list of all the taproot meetings is generated automatically. It's not strictly a component, but that field works well for general tags.

### CODE REVIEW

**Comment by jonatack** [comment]
Concept ACK!

**Comment by jonatack** [comment]
Tested ACK

**Review by jonatack — COMMENTED** [review]
Tested ACK

**Comment by jnewbery** [comment]
Thanks Jon!

**Pull request merged**
