### PR TITLE
empty commit to trigger deployment pipeline

### PR DESCRIPTION
**Pull request by stickies-v**
Do not merge - just a test to trigger the test/deployment pipeline.

### CODE REVIEW

**Comment by stickies-v** [comment]
The deployment of https://bitcoincore.reviews/25261 doesn't seem to be going through even though https://github.com/bitcoin-core-review-club/website/pull/588 was merged > 1h ago. According to the tests in this (empty) PR, it seems the Netlify build image is out of date: https://app.netlify.com/sites/bitcoincore-reviews/deploys/6373781288d950000806c781

image

@glozow @jnewbery @jonatack is anyone able to update this inside the Netlify dashboard? Not sure who has access.

**Comment by glozow** [comment]
Thanks @stickies-v, I will take care of this when I land.

**Comment by jnewbery** [comment]
I've updated the image to Ubuntu 20.04, which has unblocked new deployments. Thanks for reporting this @stickies-v!

**Comment by stickies-v** [comment]
Thank you very much @jnewbery, that should last us for another while!

**Pull request closed without merging**
