### PR TITLE
Add _posts/2020-11-04-#19905.md

### PR DESCRIPTION
**Pull request by MarcoFalke**
Still thinking about questions and notes, so this is only a placeholder :sweat_smile:

### CODE REVIEW

**Comment by jnewbery** [comment]
Thanks Marco! I've merged the announcement in #274. I think it's better not to have unfinished notes/questions, so I've left the _notes and questions to follow soon_ placeholder. Feel free to rebase this on master and update once you've completed the notes and questions.

**Comment by MarcoFalke** [comment]
Rebased

**Comment by MarcoFalke** [comment]
wen merge? :pray:

**Comment by jnewbery** [comment]
Thanks Marco!

**Pull request merged**
