### PR TITLE
announce 25515

### PR DESCRIPTION
**Pull request by LarryRuane**
https://github.com/bitcoin/bitcoin/pull/25515
@dergoegge

### CODE REVIEW

**Review by stickies-v — APPROVED** [review]
Thanks larryruane!

**Comment by glozow** [comment]
This meeting is scheduled for Wednesday, @LarryRuane do you have notes and questions?

**Comment by LarryRuane** [comment]
#572

**Comment by glozow** [comment]
No worries, thanks for the quick turnaround!

**Pull request merged**
