### PR TITLE
n16442: add 2020-05-07 meeting log (BIP157)

### PR DESCRIPTION
**Pull request by jonatack**
I don't know if you want to add this, here or somewher else, but I think it's a helpful resource.

(I reset my IRC connection at 19:01 so may have missed a line or two during that minute.)

### CODE REVIEW

**Comment by amitiuttarwar** [comment]
imo it makes more sense to add logs as an additional meeting (for 18877), with a header explaining the ad hoc context. easier to find the notes & leaves possibility for any future sessions like this

**Comment by jonatack** [comment]
> imo it makes more sense to add logs as an additional meeting (for 18877), with a header explaining the ad hoc context. easier to find the notes & leaves possibility for any future sessions like this

Thanks @amitiuttarwar. I think I prefer your suggestion too, though either way is fine with me.

**Comment by jnewbery** [comment]
Thanks for this, Jon. I've moved it to its own page as you and Amiti suggested. I agree it looks better that way. Can you take a look and merge if you're happy?

**Comment by jonatack** [comment]
ACK, thanks John and Amiti.

**Pull request merged**
