### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by jnewbery**
Make glozow the coordinator and tidy up various bits and pieces.

### CODE REVIEW

**Comment by glozow** [comment]
ACK ae186e27f0defa7db3d49317c8d77a33c30b7402

**Comment by glozow** [comment]
Oh wait, this should be updated too? 
image

**Comment by jnewbery** [comment]
> Oh wait, this should be updated too?

Good catch! Updated!

**Comment by glozow** [comment]
LGTM

**Pull request merged**
