### PR TITLE
announce-inquisition-16

### PR DESCRIPTION
**Pull request by stickies-v**

### CODE REVIEW

**Comment by stickies-v** [comment]
cc @ajtowns - already prepped the announcement since it's non-standard because of the different repo, adding notes/questions/logs is the same as usual

**Review by glozow — COMMENTED** [review]
LGTM, cc @ajtowns

**Comment by ajtowns** [comment]
Seems fine? I've drafted some notes/questions at https://github.com/ajtowns/review-club/commit/ce42565fc7b9a2e98ce0c5f90c177f5723f20eff if anyone wants to take a look? Might need to be simplified?

**Review by stickies-v — COMMENTED** [review]
Thanks @ajtowns @glozow. Fixed link to bitcoin-inquisition/bitcoin#2 and updated some phrasing/grammar. LGTM

**Comment by glozow** [comment]
Sorry, just fixed a couple more typos. LGTM

**Pull request merged**
