### PR TITLE
reschedule n27050 and add n25038-2

### PR DESCRIPTION
**Pull request by glozow**

### CODE REVIEW

**Comment by glozow** [comment]
cc @dergoegge

**Comment by dergoegge** [comment]
ACK on the reschedule, thanks!

**Review by stickies-v — APPROVED** [review]
LGTM - thx @glozow and @dergoegge!

**Comment by stickies-v** [comment]
I was trying to figure out why I couldn't merge it, but it looks like @glozow already did. Just not showing up here, so marking as closed.

**Pull request closed without merging**
